# site settings
title: tjstheiii
subtitle: an IT food blog.
email: tjstheiii+website@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "www.tjstheiii.com" # the base hostname & protocol for your site
author: "tjstheiii"
street_address: 1234 Somewhere Road
city: Coolsville
state: IL
zip_code: 55555
country: United States of America
phone: (555) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/tjstheiii/tjstheiii.com
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/thomas-j-stone-iii
  Twitter:
  Facebook: https://www.facebook.com/tjstheiii
  Slack:
  Steam: https://steamcommunity.com/id/tjstheiii/

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
